server:
  port: 9091
  servlet:
    context-path: "/legilimens/goal_service"

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: admin
      password: admin
      database: leg-goals